device: gpu
isTrain: False
num_threads: 8
batch_size: 1
shuffle: False
no_flip: True
drop_last: False
num_test: 500

root: test_img/
output_dir: test_results/
load_dir: base_model
ckp_name: CDDFuse_phase2_epoch120.pth
